import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, isOwner, requireOwner } from "../toolkit/index.js";
import { CATEGORIES, allProducts, get, nextId, now, orders, put, saveOrder, saveProduct, type Category, type Order, type Product, type Referral, type ShopUser } from "../shop.js";
import { hasAdminAccess, openAdmin, requireAdmin } from "./admin-login.js";

type AdminSession = { adminStep?: "product" | "bonus" | "message" | "user-search"; productDraft?: string[]; categoryTarget?: "new" | `edit:${string}`; messageOrderId?: string; bonusUserId?: number; usersPage?: number; usersQuery?: string; usersSort?: "name" | "orders" };
type AdminCtx = Ctx & { session: AdminSession };
const composer = new Composer<Ctx>();
const codes = ["liquids", "cartridges", "pods", "disposables"] as const;
const categories: Record<(typeof codes)[number], Category> = { liquids: "Жидкости", cartridges: "Картриджи", pods: "Pod-системы", disposables: "Одноразки" };

function clearDraft(c: AdminCtx) { c.session.adminStep = undefined; c.session.productDraft = undefined; c.session.categoryTarget = undefined; c.session.messageOrderId = undefined; c.session.bonusUserId = undefined; }
function categoryKeyboard() { return inlineKeyboard([...codes.map((code) => [inlineButton(categories[code], `admin:set-category:${code}`)]), [inlineButton("Назад", "admin:cancel-product")]]); }
function validProduct(fields: string[]) { const price = Number(fields[2]); const stock = Number(fields[3]); return (fields.length === 5 || fields.length === 6) && fields[0].length >= 2 && fields[0].length <= 80 && fields[1].length >= 3 && fields[1].length <= 1000 && fields[4].length >= 2 && Number.isFinite(price) && price > 0 && Number.isInteger(stock) && stock >= 0; }

async function showProducts(ctx: Ctx) {
  const products = await allProducts(ctx);
  const rows = products.flatMap((p) => [[inlineButton(`Изменить ${p.name}`, `admin:edit:${p.id}`)], [inlineButton(p.visibility ? `Скрыть ${p.name}` : `Показать ${p.name}`, `admin:toggle:${p.id}`)]]);
  rows.unshift([inlineButton("Добавить товар", "admin:add-product")]); rows.push([inlineButton("Назад", "admin:login")]);
  await ctx.editMessageText(products.length ? `Товары:\n${products.map((p) => `${p.name} — ${p.stock} шт.`).join("\n")}` : "Товаров пока нет — добавьте первый.", { reply_markup: inlineKeyboard(rows) });
}
async function showOrder(ctx: Ctx, order: Order) {
  const history = (order.history ?? []).map((item) => `• ${item.text}`).join("\n") || "• Заказ создан";
  await ctx.editMessageText(`Заказ ${order.id}\nСумма: ${order.total.toFixed(2)} PLN\nСтатус: ${order.status}\nИстория:\n${history}`, { reply_markup: inlineKeyboard([[inlineButton("Принят", `admin:status:${order.id}:accepted`), inlineButton("Готов", `admin:status:${order.id}:ready`)], [inlineButton("Выдан", `admin:status:${order.id}:completed`), inlineButton("Отменён", `admin:status:${order.id}:cancelled`)], [inlineButton("Отправить сообщение", `admin:message:${order.id}`)], [inlineButton("Назад", "admin:orders")]]) });
}
async function loadUsers(ctx: Ctx): Promise<ShopUser[]> { const ids = (await get<number[]>(ctx, "users:index")) ?? []; return (await Promise.all(ids.map((id) => get<ShopUser>(ctx, `user:${id}`)))).filter((u): u is ShopUser => Boolean(u)); }
async function showUsers(ctx: Ctx) {
  const c = ctx as AdminCtx; const query = (c.session.usersQuery ?? "").toLocaleLowerCase("ru"); const sort = c.session.usersSort ?? "name";
  const users = (await loadUsers(ctx)).filter((u) => !query || `${u.name} ${u.username ?? ""}`.toLocaleLowerCase("ru").includes(query)).sort((a, b) => sort === "orders" ? b.orders_count - a.orders_count || a.name.localeCompare(b.name, "ru") : a.name.localeCompare(b.name, "ru"));
  const totalPages = Math.max(1, Math.ceil(users.length / 5)); const page = Math.min(Math.max(c.session.usersPage ?? 0, 0), totalPages - 1); c.session.usersPage = page; const shown = users.slice(page * 5, page * 5 + 5);
  const rows = shown.map((u) => [inlineButton(`${u.name}${u.username ? ` @${u.username}` : ""} · заказов: ${u.orders_count}`, `admin:user:${u.telegram_id}`)]);
  if (totalPages > 1) rows.push([...(page > 0 ? [inlineButton("Назад", `admin:users-page:${page - 1}`)] : []), ...(page < totalPages - 1 ? [inlineButton("Далее", `admin:users-page:${page + 1}`)] : [])]);
  rows.push([inlineButton("Поиск", "admin:users-search"), inlineButton(sort === "name" ? "По заказам" : "По имени", `admin:users-sort:${sort === "name" ? "orders" : "name"}`)]); rows.push([inlineButton("Назад", "admin:login")]);
  await ctx.editMessageText(shown.length ? `Пользователи, страница ${page + 1} из ${totalPages}.${query ? ` Поиск: ${c.session.usersQuery}.` : ""}` : `Пользователей не найдено.${query ? ` Поиск: ${c.session.usersQuery}.` : ""}`, { reply_markup: inlineKeyboard(rows) });
}

composer.command("admin", async (ctx) => { if (!(await requireAdmin(ctx))) return; await openAdmin(ctx, false); });
composer.callbackQuery("admin:products", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; clearDraft(ctx as AdminCtx); await showProducts(ctx); });
composer.callbackQuery("admin:add-product", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const c = ctx as AdminCtx; clearDraft(c); c.session.adminStep = "product"; await ctx.editMessageText("Введите товар: название | описание | цена PLN | остаток | акцизная маркировка | фото (необязательно).", { reply_markup: inlineKeyboard([[inlineButton("Назад", "admin:cancel-product")]]) }); });
composer.callbackQuery(/^admin:edit:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const product = await get<Product>(ctx, `product:${ctx.match[1]}`); if (!product) { await ctx.editMessageText("Товар не найден."); return; } const c = ctx as AdminCtx; clearDraft(c); c.session.adminStep = "product"; c.session.categoryTarget = `edit:${product.id}`; await ctx.editMessageText("Отправьте новые данные: название | описание | цена PLN | остаток | акцизная маркировка | фото (необязательно).", { reply_markup: inlineKeyboard([[inlineButton("Назад", "admin:cancel-product")]]) }); });
composer.callbackQuery("admin:cancel-product", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; clearDraft(ctx as AdminCtx); await openAdmin(ctx, true); });
composer.callbackQuery(/^admin:toggle:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const product = await get<Product>(ctx, `product:${ctx.match[1]}`); if (!product) { await ctx.editMessageText("Товар не найден."); return; } product.visibility = !product.visibility; await saveProduct(ctx, product); await showProducts(ctx); });
composer.callbackQuery(/^admin:set-category:(liquids|cartridges|pods|disposables)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const c = ctx as AdminCtx; const draft = c.session.productDraft; const target = c.session.categoryTarget; if (!draft || !target) { await ctx.editMessageText("Изменения отменены.", { reply_markup: inlineKeyboard([[inlineButton("Назад", "admin:login")]]) }); return; } const existing = target.startsWith("edit:") ? await get<Product>(ctx, `product:${target.slice(5)}`) : undefined; if (target.startsWith("edit:") && !existing) { clearDraft(c); await ctx.editMessageText("Товар не найден."); return; } const id = existing?.id ?? await nextId(ctx, "product"); if (!id) { await ctx.editMessageText("Хранилище недоступно. Попробуйте позже."); return; } await saveProduct(ctx, { id, name: draft[0], description: draft[1], price: Number(draft[2]), stock: Number(draft[3]), excise_mark: draft[4], photo: draft[5] && draft[5] !== "-" ? draft[5] : undefined, category: categories[ctx.match[1] as (typeof codes)[number]], visibility: existing?.visibility ?? true }); const changed = target.startsWith("edit:"); clearDraft(c); await ctx.editMessageText(changed ? "Товар обновлён." : "Товар добавлен и виден в каталоге.", { reply_markup: inlineKeyboard([[inlineButton("К товарам", "admin:products")]]) }); });
composer.callbackQuery("admin:orders", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const list = await orders(ctx); await ctx.editMessageText(list.length ? list.map((o) => `${o.id}: ${o.total.toFixed(2)} PLN — ${o.status}`).join("\n") : "Заказов пока нет.", { reply_markup: inlineKeyboard([...list.map((o) => [inlineButton(`Заказ ${o.id}`, `admin:order:${o.id}`)]), [inlineButton("Назад", "admin:login")]]) }); });
composer.callbackQuery(/^admin:order:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const order = await get<Order>(ctx, `order:${ctx.match[1]}`); if (!order) { await ctx.editMessageText("Заказ не найден."); return; } await showOrder(ctx, order); });
composer.callbackQuery(/^admin:status:([^:]+):(accepted|ready|completed|cancelled)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const order = await get<Order>(ctx, `order:${ctx.match[1]}`); if (!order) { await ctx.editMessageText("Заказ не найден."); return; } order.status = ctx.match[2] as Order["status"]; order.history = [...(order.history ?? []), { timestamp: now(), kind: "status", text: `Статус изменён: ${order.status}` }]; await saveOrder(ctx, order); try { await ctx.api.sendMessage(order.client, `Статус вашего заказа: ${order.status}.`); } catch { /* A blocked user must not interrupt fulfilment. */ } await showOrder(ctx, order); });
composer.callbackQuery(/^admin:message:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const order = await get<Order>(ctx, `order:${ctx.match[1]}`); if (!order) { await ctx.editMessageText("Заказ не найден."); return; } const c = ctx as AdminCtx; clearDraft(c); c.session.adminStep = "message"; c.session.messageOrderId = order.id; await ctx.editMessageText("Напишите сообщение для покупателя.", { reply_markup: inlineKeyboard([[inlineButton("Назад", `admin:order:${order.id}`)]]) }); });
composer.callbackQuery("admin:users", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const c = ctx as AdminCtx; c.session.usersPage = 0; c.session.usersQuery = undefined; c.session.usersSort = "name"; await showUsers(ctx); });
composer.callbackQuery(/^admin:users-page:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; (ctx as AdminCtx).session.usersPage = Number(ctx.match[1]); await showUsers(ctx); });
composer.callbackQuery(/^admin:users-sort:(name|orders)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const c = ctx as AdminCtx; c.session.usersSort = ctx.match[1] as "name" | "orders"; c.session.usersPage = 0; await showUsers(ctx); });
composer.callbackQuery("admin:users-search", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const c = ctx as AdminCtx; clearDraft(c); c.session.adminStep = "user-search"; await ctx.editMessageText("Введите имя или username пользователя.", { reply_markup: inlineKeyboard([[inlineButton("Назад", "admin:users")]]) }); });
composer.callbackQuery(/^admin:user:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const user = await get<ShopUser>(ctx, `user:${ctx.match[1]}`); if (!user) { await ctx.editMessageText("Пользователь не найден."); return; } const grant = user.role !== "admin"; const action = grant ? "grant" : "revoke"; await ctx.editMessageText(`${user.name}\n${user.username ? `@${user.username}\n` : ""}Роль: ${grant ? "покупатель" : "администратор"}\nЗаказов: ${user.orders_count}`, { reply_markup: inlineKeyboard([[inlineButton(grant ? "Выдать права администратора" : "Отозвать права администратора", `admin:role:${user.telegram_id}:${action}`)], [inlineButton("Начислить бонус", `admin:bonus-user:${user.telegram_id}`)], [inlineButton("Назад", "admin:users")]]) }); });
composer.callbackQuery(/^admin:role:(\d+):(grant|revoke)$/, async (ctx) => { if (!isOwner(ctx)) { await requireOwner(ctx); return; } await ctx.answerCallbackQuery(); const label = ctx.match[2] === "grant" ? "Выдать права администратора" : "Отозвать права администратора"; await ctx.editMessageText(`Подтвердите действие: ${label}.`, { reply_markup: inlineKeyboard([[inlineButton("Подтвердить", `admin:role-confirm:${ctx.match[1]}:${ctx.match[2]}`)], [inlineButton("Назад", `admin:user:${ctx.match[1]}`)]]) }); });
composer.callbackQuery(/^admin:role-confirm:(\d+):(grant|revoke)$/, async (ctx) => { if (!isOwner(ctx)) { await requireOwner(ctx); return; } await ctx.answerCallbackQuery(); const user = await get<ShopUser>(ctx, `user:${ctx.match[1]}`); if (!user) { await ctx.editMessageText("Пользователь не найден."); return; } user.role = ctx.match[2] === "grant" ? "admin" : "customer"; await put(ctx, `user:${user.telegram_id}`, user); await ctx.editMessageText(user.role === "admin" ? "Права администратора выданы." : "Права администратора отозваны.", { reply_markup: inlineKeyboard([[inlineButton("Пользователи", "admin:users")]]) }); });
composer.callbackQuery("admin:bonus", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; await ctx.editMessageText("Выберите приглашённого пользователя в разделе «Пользователи».", { reply_markup: inlineKeyboard([[inlineButton("Пользователи", "admin:users")], [inlineButton("Назад", "admin:login")]]) }); });
composer.callbackQuery(/^admin:bonus-user:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const c = ctx as AdminCtx; clearDraft(c); c.session.adminStep = "bonus"; c.session.bonusUserId = Number(ctx.match[1]); await ctx.editMessageText("Введите сумму бонуса в PLN.", { reply_markup: inlineKeyboard([[inlineButton("Назад", `admin:user:${ctx.match[1]}`)]]) }); });
composer.on("message:text", async (ctx, next) => { const c = ctx as AdminCtx; if (!c.session.adminStep) return next(); if (!(await hasAdminAccess(ctx))) return; const text = ctx.message.text.trim(); if (c.session.adminStep === "product") { const fields = text.split("|").map((v) => v.trim()); if (!validProduct(fields)) { await ctx.reply("Проверьте данные: название | описание | цена PLN | остаток | акцизная маркировка | фото (необязательно)."); return; } c.session.productDraft = fields; c.session.categoryTarget ??= "new"; await ctx.reply("Выберите категорию товара.", { reply_markup: categoryKeyboard() }); return; } if (c.session.adminStep === "user-search") { c.session.usersQuery = text; c.session.usersPage = 0; c.session.adminStep = undefined; await showUsers(ctx); return; } if (c.session.adminStep === "bonus") { const id = c.session.bonusUserId; const amount = Number(text); const referral = id ? await get<Referral>(ctx, `referral:${id}`) : undefined; const user = id ? await get<ShopUser>(ctx, `user:${id}`) : undefined; if (!id || !Number.isFinite(amount) || amount <= 0 || !referral || !user) { await ctx.reply("Не удалось начислить бонус. Выберите приглашённого пользователя и укажите сумму больше нуля."); return; } user.discount += amount; referral.bonus += amount; await put(ctx, `user:${id}`, user); await put(ctx, `referral:${id}`, referral); clearDraft(c); await ctx.reply("Бонус начислен.", { reply_markup: inlineKeyboard([[inlineButton("Назад", `admin:user:${id}`)]]) }); return; } const order = c.session.messageOrderId ? await get<Order>(ctx, `order:${c.session.messageOrderId}`) : undefined; if (!order || !text) { await ctx.reply("Не удалось отправить сообщение. Откройте заказ ещё раз."); clearDraft(c); return; } try { await ctx.api.sendMessage(order.client, text); order.history = [...(order.history ?? []), { timestamp: now(), kind: "message", text: `Сообщение покупателю: ${text}` }]; await saveOrder(ctx, order); clearDraft(c); await ctx.reply("Сообщение отправлено и сохранено в истории.", { reply_markup: inlineKeyboard([[inlineButton("Назад", `admin:order:${order.id}`)]]) }); } catch { clearDraft(c); await ctx.reply("Не удалось доставить сообщение покупателю. Попробуйте позже.", { reply_markup: inlineKeyboard([[inlineButton("Назад", `admin:order:${order.id}`)]]) }); } });
export default composer;
