import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, requireOwner } from "../toolkit/index.js";
import { CATEGORIES, UNCATEGORIZED, allProducts, categoryOf, get, listedProducts, nextId, orders, put, saveOrder, saveProduct, type Category, type Product, type Referral, type ShopUser } from "../shop.js";
import { openAdmin } from "./admin-login.js";
type AdminCtx = Ctx & { session: { adminStep?: "product"; productDraft?: string[]; categoryTarget?: string } };
const composer = new Composer<Ctx>();
const categoryCodes = ["liquids", "cartridges", "pods", "disposables", "uncategorized"] as const;
const categories: Record<(typeof categoryCodes)[number], Category> = { liquids: "Жидкости", cartridges: "Картриджи", pods: "Pod-системы", disposables: "Одноразки", uncategorized: UNCATEGORIZED };
function categoryLabel(value: Category): string { return value === UNCATEGORIZED ? "Без категории" : value; }
function categoryKeyboard(prefix: string) { return inlineKeyboard([...categoryCodes.map((code) => [inlineButton(categoryLabel(categories[code]), `${prefix}:${code}`)]), [inlineButton("Назад", "admin:products")]]); }
composer.command("admin", async (ctx) => { if (!(await requireOwner(ctx))) return; await openAdmin(ctx, false); });
composer.callbackQuery("admin:products", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; const ps = await allProducts(ctx); await ctx.editMessageText(ps.length ? `Товары:\n${ps.map((p) => `${p.name} — ${categoryLabel(categoryOf(p.category))} (${p.stock} шт.)`).join("\n")}` : "Товаров пока нет.", { reply_markup: inlineKeyboard([[inlineButton("Добавить товар", "admin:add-product")], [inlineButton("Назначить категорию всем", "admin:bulk-category")], ...ps.flatMap((p) => [[inlineButton(p.visibility ? `Скрыть ${p.name}` : `Показать ${p.name}`, `admin:toggle:${p.id}`)], [inlineButton(`Категория: ${p.name}`, `admin:edit-category:${p.id}`)]]), [inlineButton("Назад", "admin:login")]]) }); });
composer.callbackQuery("admin:add-product", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; const c = ctx as AdminCtx; c.session.adminStep = "product"; c.session.productDraft = []; await ctx.editMessageText("Введите товар: название | описание | цена PLN | остаток | акцизная маркировка."); });
composer.on("message:text", async (ctx, next) => { const c = ctx as AdminCtx; if (c.session.adminStep !== "product") return next(); if (!(await requireOwner(ctx))) return; const fields = ctx.message.text.split("|").map((s) => s.trim()); const price = Number(fields[2]); const stock = Number(fields[3]); if (fields.length !== 5 || !fields[0] || !fields[1] || !fields[4] || !Number.isFinite(price) || price <= 0 || !Number.isInteger(stock) || stock < 0) { await ctx.reply("Проверьте формат: название | описание | цена PLN | остаток | акцизная маркировка."); return; } c.session.adminStep = undefined; c.session.productDraft = fields; c.session.categoryTarget = "new"; await ctx.reply("Выберите категорию товара.", { reply_markup: categoryKeyboard("admin:set-category") }); });
composer.callbackQuery(/^admin:edit-category:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; (ctx as AdminCtx).session.categoryTarget = ctx.match[1]; await ctx.editMessageText("Выберите новую категорию.", { reply_markup: categoryKeyboard("admin:set-category") }); });
composer.callbackQuery("admin:bulk-category", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; (ctx as AdminCtx).session.categoryTarget = "all"; await ctx.editMessageText("Выберите категорию для всех товаров.", { reply_markup: categoryKeyboard("admin:set-category") }); });
composer.callbackQuery(/^admin:set-category:(liquids|cartridges|pods|disposables|uncategorized)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; const c = ctx as AdminCtx; const category = categories[ctx.match[1] as (typeof categoryCodes)[number]]; if (c.session.categoryTarget === "new" && c.session.productDraft) { const fields = c.session.productDraft; const id = await nextId(ctx, "product"); if (!id) { await ctx.editMessageText("Хранилище недоступно. Попробуйте позже."); return; } await saveProduct(ctx, { id, name: fields[0], description: fields[1], price: Number(fields[2]), stock: Number(fields[3]), excise_mark: fields[4], category, visibility: true }); c.session.productDraft = undefined; c.session.categoryTarget = undefined; await ctx.editMessageText("Товар добавлен и виден в каталоге.", { reply_markup: inlineKeyboard([[inlineButton("К товарам", "admin:products")]]) }); return; }
  if (c.session.categoryTarget === "all") { const products = await allProducts(ctx); for (const product of products) { product.category = category; await saveProduct(ctx, product); } c.session.categoryTarget = undefined; await ctx.editMessageText("Категория назначена всем товарам.", { reply_markup: inlineKeyboard([[inlineButton("К товарам", "admin:products")]]) }); return; }
  const product = c.session.categoryTarget ? await get<Product>(ctx, `product:${c.session.categoryTarget}`) : undefined; if (!product) { await ctx.editMessageText("Товар не найден."); return; } product.category = category; await saveProduct(ctx, product); c.session.categoryTarget = undefined; await ctx.editMessageText("Категория товара обновлена.", { reply_markup: inlineKeyboard([[inlineButton("К товарам", "admin:products")]]) }); });
composer.callbackQuery(/^admin:toggle:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; const p = await get<Product>(ctx, `product:${ctx.match[1]}`); if (!p) { await ctx.editMessageText("Товар не найден."); return; } p.visibility = !p.visibility; await saveProduct(ctx, p); await ctx.editMessageText(p.visibility ? "Товар снова виден в каталоге." : "Товар скрыт из каталога.", { reply_markup: inlineKeyboard([[inlineButton("К товарам", "admin:products")]]) }); });
composer.callbackQuery("admin:orders", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; const list = await orders(ctx); if (!list.length) { await ctx.editMessageText("Новых заказов нет.", { reply_markup: inlineKeyboard([[inlineButton("Назад", "admin:login")]]) }); return; } await ctx.editMessageText(list.map((o) => `${o.id}: ${o.total.toFixed(2)} PLN — ${o.status}`).join("\n"), { reply_markup: inlineKeyboard([...list.filter((o) => o.status !== "completed" && o.status !== "cancelled").map((o) => [inlineButton(`Статус ${o.id}`, `admin:order:${o.id}`)]), [inlineButton("Назад", "admin:login")]]) }); });
composer.callbackQuery(/^admin:order:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; const order = await get<import("../shop.js").Order>(ctx, `order:${ctx.match[1]}`); if (!order) { await ctx.editMessageText("Заказ не найден."); return; } await ctx.editMessageText(`Заказ ${order.id}: выберите статус.`, { reply_markup: inlineKeyboard([[inlineButton("Принят", `admin:status:${order.id}:accepted`), inlineButton("Готов", `admin:status:${order.id}:ready`)], [inlineButton("Выдан", `admin:status:${order.id}:completed`), inlineButton("Отменён", `admin:status:${order.id}:cancelled`)], [inlineButton("К заказам", "admin:orders")]]) }); });
composer.callbackQuery(/^admin:status:([^:]+):(accepted|ready|completed|cancelled)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; const order = await get<import("../shop.js").Order>(ctx, `order:${ctx.match[1]}`); if (!order) { await ctx.editMessageText("Заказ не найден."); return; } order.status = ctx.match[2] as import("../shop.js").Order["status"]; await saveOrder(ctx, order); try { await ctx.api.sendMessage(order.client, `Статус вашего заказа изменён: ${order.status}.`); } catch { /* user may have blocked the bot */ } await ctx.editMessageText("Статус заказа обновлён.", { reply_markup: inlineKeyboard([[inlineButton("К заказам", "admin:orders")]]) }); });
composer.callbackQuery("admin:users", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; await ctx.editMessageText("Бонус можно начислить приглашённому пользователю после проверки реферала.", { reply_markup: inlineKeyboard([[inlineButton("Начислить бонус", "admin:bonus")], [inlineButton("Назад", "admin:login")]]) }); });
composer.callbackQuery("admin:bonus", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ctx))) return; await ctx.editMessageText("Отправьте Telegram ID приглашённого пользователя и сумму через пробел."); (ctx as AdminCtx).session.adminStep = undefined; (ctx as AdminCtx).session.productDraft = ["bonus"]; });
composer.on("message:text", async (ctx, next) => { const c = ctx as AdminCtx; if (c.session.productDraft?.[0] !== "bonus") return next(); if (!(await requireOwner(ctx))) return; const [idText, amountText] = ctx.message.text.trim().split(/\s+/); const id = Number(idText), amount = Number(amountText); const referral = await get<Referral>(ctx, `referral:${id}`); const user = await get<ShopUser>(ctx, `user:${id}`); if (!Number.isSafeInteger(id) || !Number.isFinite(amount) || amount <= 0 || !referral || !user) { await ctx.reply("Не удалось подтвердить реферала. Проверьте ID и сумму."); return; } user.discount += amount; referral.bonus += amount; await put(ctx, `user:${id}`, user); await put(ctx, `referral:${id}`, referral); c.session.productDraft = undefined; await ctx.reply("Бонус начислен.", { reply_markup: inlineKeyboard([[inlineButton("К админ-панели", "admin:login")]]) }); });
export default composer;
