import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, isOwner, requireOwner } from "../toolkit/index.js";
import { CATEGORIES, allProducts, get, nextId, now, orders, put, saveOrder, saveProduct, type Category, type Order, type Product, type Referral, type ShopUser } from "../shop.js";
import { hasAdminAccess, openAdmin, requireAdmin } from "./admin-login.js";

type AdminSession = { adminStep?: "product" | "bonus" | "message"; productDraft?: string[]; categoryTarget?: string; messageOrderId?: string };
type AdminCtx = Ctx & { session: AdminSession };
const composer = new Composer<Ctx>();
const codes = ["liquids", "cartridges", "pods", "disposables"] as const;
const categories: Record<(typeof codes)[number], Category> = { liquids: "Жидкости", cartridges: "Картриджи", pods: "Pod-системы", disposables: "Одноразки" };

function clearDraft(c: AdminCtx) { c.session.adminStep = undefined; c.session.productDraft = undefined; c.session.categoryTarget = undefined; c.session.messageOrderId = undefined; }
function categoryKeyboard() { return inlineKeyboard([...codes.map((code) => [inlineButton(categories[code], `admin:set-category:${code}`)]), [inlineButton("Назад", "admin:cancel-product")]]); }
async function showProducts(ctx: Ctx) {
  const products = await allProducts(ctx);
  const rows = products.flatMap((p) => [[inlineButton(p.visibility ? `Скрыть ${p.name}` : `Показать ${p.name}`, `admin:toggle:${p.id}`)]]);
  rows.unshift([inlineButton("Добавить товар", "admin:add-product")]);
  rows.push([inlineButton("Назад", "admin:login")]);
  await ctx.editMessageText(products.length ? `Товары:\n${products.map((p) => `${p.name} — ${p.stock} шт.`).join("\n")}` : "Товаров пока нет — добавьте первый.", { reply_markup: inlineKeyboard(rows) });
}
async function showOrder(ctx: Ctx, order: Order) {
  const history = (order.history ?? []).map((item) => `• ${item.text}`).join("\n") || "• Заказ создан";
  await ctx.editMessageText(`Заказ ${order.id}\nСумма: ${order.total.toFixed(2)} PLN\nСтатус: ${order.status}\nИстория:\n${history}`, { reply_markup: inlineKeyboard([
    [inlineButton("Принят", `admin:status:${order.id}:accepted`), inlineButton("Готов", `admin:status:${order.id}:ready`)],
    [inlineButton("Выдан", `admin:status:${order.id}:completed`), inlineButton("Отменён", `admin:status:${order.id}:cancelled`)],
    [inlineButton("Отправить сообщение", `admin:message:${order.id}`)],
    [inlineButton("Назад", "admin:orders")],
  ]) });
}

composer.command("admin", async (ctx) => { if (!(await requireAdmin(ctx))) return; await openAdmin(ctx, false); });
composer.callbackQuery("admin:products", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; clearDraft(ctx as AdminCtx); await showProducts(ctx); });
composer.callbackQuery("admin:add-product", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const c = ctx as AdminCtx; clearDraft(c); c.session.adminStep = "product"; await ctx.editMessageText("Введите товар: название | описание | цена PLN | остаток | акцизная маркировка | фото (необязательно).", { reply_markup: inlineKeyboard([[inlineButton("Назад", "admin:cancel-product")]]) }); });
composer.callbackQuery("admin:cancel-product", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; clearDraft(ctx as AdminCtx); await openAdmin(ctx, true); });
composer.callbackQuery(/^admin:toggle:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const product = await get<Product>(ctx, `product:${ctx.match[1]}`); if (!product) { await ctx.editMessageText("Товар не найден."); return; } product.visibility = !product.visibility; await saveProduct(ctx, product); await showProducts(ctx); });
composer.callbackQuery(/^admin:set-category:(liquids|cartridges|pods|disposables)$/, async (ctx) => {
  await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return;
  const c = ctx as AdminCtx; const draft = c.session.productDraft;
  if (!draft || c.session.categoryTarget !== "new") { await ctx.editMessageText("Создание товара отменено.", { reply_markup: inlineKeyboard([[inlineButton("Назад", "admin:login")]]) }); return; }
  const id = await nextId(ctx, "product");
  if (!id) { await ctx.editMessageText("Хранилище недоступно. Попробуйте позже."); return; }
  await saveProduct(ctx, { id, name: draft[0], description: draft[1], price: Number(draft[2]), stock: Number(draft[3]), excise_mark: draft[4], photo: draft[5] && draft[5] !== "-" ? draft[5] : undefined, category: categories[ctx.match[1] as (typeof codes)[number]], visibility: true });
  clearDraft(c); await ctx.editMessageText("Товар добавлен и виден в каталоге.", { reply_markup: inlineKeyboard([[inlineButton("К товарам", "admin:products")]]) });
});
composer.callbackQuery("admin:orders", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const list = await orders(ctx); await ctx.editMessageText(list.length ? list.map((o) => `${o.id}: ${o.total.toFixed(2)} PLN — ${o.status}`).join("\n") : "Заказов пока нет.", { reply_markup: inlineKeyboard([...list.map((o) => [inlineButton(`Заказ ${o.id}`, `admin:order:${o.id}`)]), [inlineButton("Назад", "admin:login")]]) }); });
composer.callbackQuery(/^admin:order:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const order = await get<Order>(ctx, `order:${ctx.match[1]}`); if (!order) { await ctx.editMessageText("Заказ не найден."); return; } await showOrder(ctx, order); });
composer.callbackQuery(/^admin:status:([^:]+):(accepted|ready|completed|cancelled)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const order = await get<Order>(ctx, `order:${ctx.match[1]}`); if (!order) { await ctx.editMessageText("Заказ не найден."); return; } order.status = ctx.match[2] as Order["status"]; order.history = [...(order.history ?? []), { timestamp: now(), kind: "status", text: `Статус изменён: ${order.status}` }]; await saveOrder(ctx, order); try { await ctx.api.sendMessage(order.client, `Статус вашего заказа: ${order.status}.`); } catch { /* blocked users must not block order processing */ } await showOrder(ctx, order); });
composer.callbackQuery(/^admin:message:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const order = await get<Order>(ctx, `order:${ctx.match[1]}`); if (!order) { await ctx.editMessageText("Заказ не найден."); return; } const c = ctx as AdminCtx; clearDraft(c); c.session.adminStep = "message"; c.session.messageOrderId = order.id; await ctx.editMessageText("Напишите сообщение для покупателя.", { reply_markup: inlineKeyboard([[inlineButton("Назад", `admin:order:${order.id}`)]]) }); });
composer.callbackQuery("admin:users", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const ids = (await get<number[]>(ctx, "users:index")) ?? []; const users = (await Promise.all(ids.map((id) => get<ShopUser>(ctx, `user:${id}`)))).filter((u): u is ShopUser => Boolean(u)); const rows = users.map((u) => [inlineButton(`${u.name}${u.username ? ` @${u.username}` : ""} — ${u.telegram_id}`, `admin:user:${u.telegram_id}`)]); rows.push([inlineButton("Назад", "admin:login")]); await ctx.editMessageText(users.length ? `Пользователи:\n${users.map((u) => `${u.name}${u.username ? ` @${u.username}` : ""} — ${u.telegram_id}`).join("\n")}` : "Пользователей пока нет.", { reply_markup: inlineKeyboard(rows) }); });
composer.callbackQuery(/^admin:user:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const user = await get<ShopUser>(ctx, `user:${ctx.match[1]}`); if (!user) { await ctx.editMessageText("Пользователь не найден."); return; } const grant = user.role !== "admin"; const action = grant ? "grant" : "revoke"; const label = grant ? "Выдать админку" : "Отозвать админку"; await ctx.editMessageText(`${user.name}\n${user.username ? `@${user.username}\n` : ""}ID: ${user.telegram_id}\nРоль: ${grant ? "покупатель" : "администратор"}`, { reply_markup: inlineKeyboard([[inlineButton(label, `admin:role:${user.telegram_id}:${action}`)], [inlineButton("Назад", "admin:users")]]) }); });
composer.callbackQuery(/^admin:role:(\d+):(grant|revoke)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!isOwner(ctx)) { await requireOwner(ctx); return; } const label = ctx.match[2] === "grant" ? "Выдать админку" : "Отозвать админку"; await ctx.editMessageText(`Подтвердите действие: ${label}.`, { reply_markup: inlineKeyboard([[inlineButton("Подтвердить", `admin:role-confirm:${ctx.match[1]}:${ctx.match[2]}`)], [inlineButton("Назад", `admin:user:${ctx.match[1]}`)]]) }); });
composer.callbackQuery(/^admin:role-confirm:(\d+):(grant|revoke)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!isOwner(ctx)) { await requireOwner(ctx); return; } const user = await get<ShopUser>(ctx, `user:${ctx.match[1]}`); if (!user) { await ctx.editMessageText("Пользователь не найден."); return; } user.role = ctx.match[2] === "grant" ? "admin" : "customer"; await put(ctx, `user:${user.telegram_id}`, user); await ctx.editMessageText(user.role === "admin" ? "Права администратора выданы." : "Права администратора отозваны.", { reply_markup: inlineKeyboard([[inlineButton("Пользователи", "admin:users")]]) }); });
composer.callbackQuery("admin:bonus", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireAdmin(ctx))) return; const c = ctx as AdminCtx; clearDraft(c); c.session.adminStep = "bonus"; await ctx.editMessageText("Отправьте ID приглашённого пользователя и сумму через пробел.", { reply_markup: inlineKeyboard([[inlineButton("Назад", "admin:login")]]) }); });
composer.on("message:text", async (ctx, next) => { const c = ctx as AdminCtx; if (!c.session.adminStep) return next(); if (!(await hasAdminAccess(ctx))) return; const text = ctx.message.text.trim(); if (c.session.adminStep === "product") { const fields = text.split("|").map((v) => v.trim()); const price = Number(fields[2]); const stock = Number(fields[3]); if ((fields.length !== 5 && fields.length !== 6) || !fields[0] || !fields[1] || !fields[4] || !Number.isFinite(price) || price <= 0 || !Number.isInteger(stock) || stock < 0) { await ctx.reply("Проверьте формат: название | описание | цена PLN | остаток | акцизная маркировка | фото (необязательно)."); return; } c.session.productDraft = fields; c.session.categoryTarget = "new"; await ctx.reply("Выберите категорию товара.", { reply_markup: categoryKeyboard() }); return; }
  if (c.session.adminStep === "bonus") { const [idText, amountText] = text.split(/\s+/); const id = Number(idText); const amount = Number(amountText); const referral = await get<Referral>(ctx, `referral:${id}`); const user = await get<ShopUser>(ctx, `user:${id}`); if (!Number.isSafeInteger(id) || !Number.isFinite(amount) || amount <= 0 || !referral || !user) { await ctx.reply("Не удалось подтвердить реферала. Проверьте ID и сумму."); return; } user.discount += amount; referral.bonus += amount; await put(ctx, `user:${id}`, user); await put(ctx, `referral:${id}`, referral); clearDraft(c); await ctx.reply("Бонус начислен.", { reply_markup: inlineKeyboard([[inlineButton("Назад", "admin:login")]]) }); return; }
  const order = c.session.messageOrderId ? await get<Order>(ctx, `order:${c.session.messageOrderId}`) : undefined; if (!order || !text) { await ctx.reply("Не удалось отправить сообщение. Откройте заказ ещё раз."); clearDraft(c); return; } try { await ctx.api.sendMessage(order.client, text); order.history = [...(order.history ?? []), { timestamp: now(), kind: "message", text: `Сообщение покупателю: ${text}` }]; await saveOrder(ctx, order); clearDraft(c); await ctx.reply("Сообщение отправлено и сохранено в истории.", { reply_markup: inlineKeyboard([[inlineButton("Назад", `admin:order:${order.id}`)]]) }); } catch { clearDraft(c); await ctx.reply("Не удалось доставить сообщение покупателю. Попробуйте позже.", { reply_markup: inlineKeyboard([[inlineButton("Назад", `admin:order:${order.id}`)]]) }); }
});
export default composer;
